# Generated by Django 5.0 on 2023-12-30 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=10)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('image', models.URLField()),
                ('production_year', models.PositiveSmallIntegerField()),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')])),
                ('horsepower', models.PositiveSmallIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EliteDriveDealsApp.dealer')),
            ],
        ),
    ]
