# Generated by Django 5.0 on 2023-12-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EliteDriveDealsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.URLField(max_length=255),
        ),
    ]
