# Generated by Django 5.0 on 2024-01-01 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EliteDriveDealsApp', '0004_alter_car_brand_alter_car_mileage_alter_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='city',
            field=models.CharField(choices=[('S', 'Sofia'), ('P', 'Plovdiv'), ('V', 'Varna'), ('B', 'Burgas'), ('R', 'Ruse'), ('ST', 'Stara Zagora'), ('VT', 'Veliko Tarnovo'), ('SL', 'Sliven')]),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
