# Generated by Django 5.0 on 2024-01-02 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EliteDriveDealsApp', '0005_alter_dealer_city_alter_dealer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='posted_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic')]),
        ),
    ]
