# Generated by Django 5.0 on 2024-01-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EliteDriveDealsApp', '0006_car_posted_on_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EliteDriveDealsApp.dealer'),
        ),
    ]
