# Generated by Django 5.0 on 2024-01-04 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EliteDriveDealsApp', '0009_rename_city_dealer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='production_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('', 'Transmission'), ('Manual', 'Manual'), ('Automatic', 'Automatic')]),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='location',
            field=models.CharField(choices=[('', 'Location'), ('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Ruse', 'Ruse'), ('Stara Zagora', 'Stara Zagora'), ('Veliko Tarnovo', 'Veliko Tarnovo'), ('Sliven', 'Sliven')]),
        ),
    ]
