# Generated by Django 5.0 on 2024-01-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EliteDriveDealsApp', '0010_alter_car_production_year_alter_car_transmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=15),
        ),
    ]
