# Generated by Django 5.0 on 2024-01-05 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EliteDriveDealsApp', '0012_alter_dealer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='production_year',
            new_name='manufacture_year',
        ),
        migrations.AlterField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='EliteDriveDealsApp.dealer'),
        ),
    ]
