# Generated by Django 5.0 on 2024-01-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EliteDriveDealsApp', '0013_rename_production_year_car_manufacture_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
