# Generated by Django 5.0 on 2024-01-13 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EliteDriveDealsApp', '0014_car_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
